"""
AI Image Detection Service
══════════════════════════════════════════════════════════════
Primary model : openai/clip-vit-base-patch16  (zero-shot)
Pixel forensics: DCT high-frequency energy, noise uniformity,
                 colour channel correlation
EXIF analysis : generation software markers, GPS absence,
                suspicious creation tools

CLIP zero-shot approach
───────────────────────
CLIP encodes both an image and a set of text prompts into a shared
embedding space, then returns cosine-similarity scores.

We compare the image against two prompt groups:

  REAL prompts  (high similarity → real photograph)
    "a real photograph taken by a camera"
    "a natural photo with realistic lighting and texture"
    "an authentic image captured by a human photographer"

  AI prompts    (high similarity → AI-generated)
    "an AI-generated image created by a neural network"
    "a synthetic image generated by a diffusion model"
    "a computer-generated deepfake image"

softmax over all prompts → probability per label →
  ai_percent   = mean probability of AI prompts
  real_percent = mean probability of real prompts

Pixel forensics (runs regardless of model availability)
───────────────
1. DCT frequency analysis — AI images have unnaturally smooth
   high-frequency components; natural photos have camera sensor noise.
2. Noise uniformity — GAN/diffusion outputs have suspiciously
   uniform noise variance across regions.
3. Colour channel correlation — AI images often show slightly
   too-perfect correlations between R, G, B channels.

EXIF inspection
───────────────
Reads EXIF tags via Pillow.  Flags:
  • Software tag containing "diffusion", "midjourney", "stable",
    "dalle", "firefly", "gen-2", "runway", "comfy"
  • Missing GPS (expected in most modern phone photos)
  • Unusually early or suspiciously round creation timestamps
  • No camera make/model (AI output has no hardware origin)

Exported surface
────────────────
  analyze_image(image_b64)  →  full result dict
"""

from __future__ import annotations

import asyncio
import base64
import io
import logging
import math
import time
from typing import Any

log = logging.getLogger("aiproof.ai_image")

# ── Model config ──────────────────────────────────────────────────────────────

MODEL_ID    = "openai/clip-vit-base-patch16"
MODEL_NAME  = "CLIP ViT-B/16"
MODEL_WEIGHT = 0.40

# ── Zero-shot prompt groups ───────────────────────────────────────────────────

_REAL_PROMPTS = [
    "a real photograph taken by a camera",
    "a natural photo with realistic lighting and texture",
    "an authentic image captured by a human photographer",
]

_AI_PROMPTS = [
    "an AI-generated image created by a neural network",
    "a synthetic image generated by a diffusion model",
    "a computer-generated deepfake or GAN image",
]

# ── AI software EXIF markers ──────────────────────────────────────────────────

_AI_SOFTWARE_MARKERS = [
    "stable diffusion", "midjourney", "dalle", "dall-e",
    "firefly", "gen-2", "runway", "comfy", "automatic1111",
    "novelai", "invoke", "dream", "artbreeder",
]

# ── Pipeline singleton ────────────────────────────────────────────────────────

_model      = None   # CLIPModel
_processor  = None   # CLIPProcessor
_load_error: str | None = None


def _load_model() -> None:
    global _model, _processor, _load_error
    try:
        from transformers import CLIPModel, CLIPProcessor
        log.info("Loading %s …", MODEL_ID)
        t0 = time.time()
        _processor = CLIPProcessor.from_pretrained(MODEL_ID)
        _model     = CLIPModel.from_pretrained(MODEL_ID)
        _model.eval()
        log.info("%s loaded in %.1fs", MODEL_ID, time.time() - t0)
    except Exception as exc:
        _load_error = str(exc)
        log.warning("Could not load %s (%s) — pixel-forensics only", MODEL_ID, exc)


_load_model()


# ── Image decoding ────────────────────────────────────────────────────────────

def _decode_image(image_b64: str):
    """
    Decode base64 → PIL Image (RGB).
    Raises ValueError on invalid input.
    """
    try:
        from PIL import Image
    except ImportError:
        raise ValueError("Pillow is not installed")

    # Strip data-URI prefix if present
    if "," in image_b64:
        image_b64 = image_b64.split(",", 1)[1]

    try:
        raw   = base64.b64decode(image_b64)
        image = Image.open(io.BytesIO(raw)).convert("RGB")
        return image, raw
    except Exception as exc:
        raise ValueError(f"Cannot decode image: {exc}") from exc


# ── CLIP zero-shot inference ──────────────────────────────────────────────────

def _run_clip(image) -> tuple[float, float, float]:
    """
    Blocking — offload with asyncio.to_thread().
    Returns (ai_pct, real_pct, confidence).
    """
    import torch

    all_prompts  = _REAL_PROMPTS + _AI_PROMPTS
    n_real       = len(_REAL_PROMPTS)

    inputs = _processor(
        text=all_prompts,
        images=image,
        return_tensors="pt",
        padding=True,
    )

    with torch.no_grad():
        outputs     = _model(**inputs)
        logits      = outputs.logits_per_image[0]   # shape: (n_prompts,)
        probs       = torch.softmax(logits, dim=0).tolist()

    real_prob = sum(probs[:n_real]) / n_real
    ai_prob   = sum(probs[n_real:]) / len(_AI_PROMPTS)

    # Renormalise to sum to 100
    total     = real_prob + ai_prob
    ai_pct    = round((ai_prob  / total) * 100, 2) if total else 50.0
    real_pct  = round((real_prob / total) * 100, 2) if total else 50.0

    # Confidence = decisiveness (distance from 50%)
    confidence = round(abs(ai_pct / 100 - 0.5) * 2, 4)

    return ai_pct, real_pct, confidence


# ── Pixel forensics ───────────────────────────────────────────────────────────

def _pixel_forensics(image) -> dict[str, Any]:
    """
    Run three pixel-level tests using only numpy + stdlib.
    Returns a dict of signals and a composite suspicion score (0–100,
    higher = more likely AI-generated).
    """
    try:
        import numpy as np
    except ImportError:
        return {"score": 50, "signals": [], "error": "numpy not available"}

    img_arr = np.array(image, dtype=np.float32)
    h, w, _ = img_arr.shape

    signals  = []
    score_components: list[float] = []

    # ── 1. DCT high-frequency energy ────────────────────────────────────────
    # Convert to greyscale, compute 8×8 block DCT, measure ratio of
    # high-freq (AC) energy vs low-freq energy.
    # AI images: suspiciously smooth → low HF ratio → high AI score.
    try:
        grey  = img_arr.mean(axis=2)
        # Sample 16 random 8×8 blocks
        hf_ratios = []
        for _ in range(16):
            ry = max(0, min(h - 8, int(np.random.rand() * (h - 8))))
            rx = max(0, min(w - 8, int(np.random.rand() * (w - 8))))
            block  = grey[ry:ry+8, rx:rx+8]
            dct    = _dct2(block)
            dc     = float(dct[0, 0] ** 2)
            ac     = float((dct ** 2).sum() - dc)
            hf_ratios.append(ac / (dc + 1e-6))

        avg_hf = float(np.mean(hf_ratios))
        # Typical natural image: avg_hf > 0.3
        # AI image: avg_hf < 0.15
        if avg_hf < 0.12:
            dct_score = 80.0
            signals.append({"type": "dct-frequency", "label": "Unnaturally smooth frequency spectrum", "strength": 0.85})
        elif avg_hf < 0.22:
            dct_score = 55.0
            signals.append({"type": "dct-frequency", "label": "Low high-frequency energy", "strength": 0.55})
        else:
            dct_score = 25.0
            signals.append({"type": "dct-frequency", "label": "Natural camera noise pattern", "strength": 0.20})
        score_components.append(dct_score)

    except Exception as e:
        log.debug("DCT analysis failed: %s", e)

    # ── 2. Noise uniformity ──────────────────────────────────────────────────
    # Divide image into 4×4 grid, measure local std-dev per cell.
    # AI images show suspiciously uniform variance across regions.
    try:
        cell_h, cell_w = h // 4, w // 4
        local_stds = []
        for i in range(4):
            for j in range(4):
                cell = grey[i*cell_h:(i+1)*cell_h, j*cell_w:(j+1)*cell_w]
                local_stds.append(float(np.std(cell)))

        std_of_stds = float(np.std(local_stds))  # low = uniform = AI
        if std_of_stds < 3.0:
            noise_score = 75.0
            signals.append({"type": "noise-uniformity", "label": "Suspiciously uniform noise across regions", "strength": 0.80})
        elif std_of_stds < 8.0:
            noise_score = 45.0
            signals.append({"type": "noise-uniformity", "label": "Slightly uniform noise distribution", "strength": 0.45})
        else:
            noise_score = 20.0
            signals.append({"type": "noise-uniformity", "label": "Natural regional noise variation", "strength": 0.15})
        score_components.append(noise_score)

    except Exception as e:
        log.debug("Noise analysis failed: %s", e)

    # ── 3. Colour channel correlation ────────────────────────────────────────
    # AI-generated images often have near-perfect R↔G↔B correlations
    # because generators learn global colour statistics.
    try:
        r, g, b = img_arr[:, :, 0].flatten(), img_arr[:, :, 1].flatten(), img_arr[:, :, 2].flatten()
        corr_rg = float(np.corrcoef(r, g)[0, 1])
        corr_rb = float(np.corrcoef(r, b)[0, 1])
        avg_corr = (abs(corr_rg) + abs(corr_rb)) / 2

        if avg_corr > 0.97:
            colour_score = 70.0
            signals.append({"type": "colour-correlation", "label": "Unnaturally high channel correlation", "strength": 0.75})
        elif avg_corr > 0.90:
            colour_score = 40.0
            signals.append({"type": "colour-correlation", "label": "Elevated colour channel correlation", "strength": 0.40})
        else:
            colour_score = 15.0
        score_components.append(colour_score)

    except Exception as e:
        log.debug("Colour analysis failed: %s", e)

    composite = round(sum(score_components) / len(score_components), 2) if score_components else 50.0
    return {"score": composite, "signals": signals}


def _dct2(block):
    """Compute 2D DCT via separable 1D transforms (no scipy needed)."""
    import numpy as np
    n = block.shape[0]
    result = np.zeros_like(block)
    # Row DCT
    for i in range(n):
        result[i] = _dct1d(block[i])
    # Column DCT
    for j in range(n):
        result[:, j] = _dct1d(result[:, j])
    return result


def _dct1d(x):
    """Type-II DCT (unnormalized), pure numpy."""
    import numpy as np
    n = len(x)
    result = np.zeros(n)
    for k in range(n):
        result[k] = sum(
            x[i] * math.cos(math.pi * k * (2 * i + 1) / (2 * n))
            for i in range(n)
        )
    return result


# ── EXIF analysis ─────────────────────────────────────────────────────────────

def _exif_analysis(raw_bytes: bytes) -> dict[str, Any]:
    """
    Extract EXIF metadata and flag AI-generation markers.
    Returns { score, signals, metadata }.
    score = 0–100 (higher → more likely AI-generated).
    """
    signals  = []
    metadata = {}
    score    = 0.0

    try:
        from PIL import Image, ExifTags
        import io as _io

        img  = Image.open(_io.BytesIO(raw_bytes))
        exif_raw = img._getexif() if hasattr(img, '_getexif') else None
        exif = {}
        if exif_raw:
            exif = {
                ExifTags.TAGS.get(k, k): v
                for k, v in exif_raw.items()
            }

        # No EXIF at all — common for AI outputs
        if not exif:
            score += 25
            signals.append({"type": "exif-absent", "label": "No EXIF metadata (common in AI images)", "strength": 0.60})
            metadata["hasExif"] = False
        else:
            metadata["hasExif"] = True

            # Software tag check
            software = str(exif.get("Software", "")).lower()
            metadata["software"] = exif.get("Software", None)
            for marker in _AI_SOFTWARE_MARKERS:
                if marker in software:
                    score += 60
                    signals.append({"type": "exif-software", "label": f"AI software detected: {exif.get('Software')}", "strength": 0.95})
                    break

            # No camera make/model
            has_make  = bool(exif.get("Make"))
            has_model = bool(exif.get("Model"))
            metadata["cameraMake"]  = exif.get("Make",  None)
            metadata["cameraModel"] = exif.get("Model", None)
            if not has_make and not has_model:
                score += 20
                signals.append({"type": "exif-no-camera", "label": "No camera make/model in metadata", "strength": 0.50})

            # GPS absence (most modern phones embed GPS)
            has_gps = "GPSInfo" in exif
            metadata["hasGPS"] = has_gps
            if not has_gps:
                score += 10
                signals.append({"type": "exif-no-gps", "label": "No GPS data (expected in phone photos)", "strength": 0.30})

        metadata["width"]  = img.width
        metadata["height"] = img.height
        metadata["format"] = img.format

    except ImportError:
        metadata["pillow"] = "not installed"
    except Exception as exc:
        log.debug("EXIF analysis error: %s", exc)

    return {
        "score":   round(min(100, score), 2),
        "signals": signals,
        "metadata": metadata,
    }


# ── Pure-Python heuristic fallback ────────────────────────────────────────────

def _heuristic_fallback(image_b64: str, raw_bytes: bytes) -> tuple[float, float, float]:
    """
    Fallback when CLIP is not available.
    Uses base64 entropy as a rough proxy for image complexity.
    Natural photos have higher entropy (more varied byte patterns).
    """
    # Byte-value entropy of raw image bytes (first 64KB sample)
    sample = raw_bytes[:65536]
    if not sample:
        return 50.0, 50.0, 0.3

    counts = [0] * 256
    for b in sample:
        counts[b] += 1

    n       = len(sample)
    entropy = -sum((c / n) * math.log2(c / n) for c in counts if c > 0)
    # Natural compressed JPEG: entropy ≈ 7.5–8.0
    # AI PNG (often less compressed): entropy ≈ 6.5–7.5
    # Very low entropy may indicate synthetic flat regions

    if entropy > 7.6:
        ai_pct = 25.0
    elif entropy > 7.0:
        ai_pct = 45.0
    else:
        ai_pct = 65.0

    real_pct   = round(100 - ai_pct, 2)
    confidence = 0.35   # always low for heuristic
    return round(ai_pct, 2), real_pct, confidence


# ── Public entry point ────────────────────────────────────────────────────────

async def analyze_image(image_b64: str) -> dict[str, Any]:
    """
    Analyze a base64-encoded image for AI-generation signals.

    Pipeline:
      1. Decode image bytes
      2. EXIF inspection (always runs)
      3. Pixel forensics — DCT, noise, colour (always runs)
      4. CLIP zero-shot classification (if model loaded)
      5. Combine signals into weighted verdict

    Returns:
        {
          "trustScore":   int,      // 0–100 (100 = authentic)
          "ai_percent":   float,
          "real_percent": float,
          "confidence":   float,
          "verdict":      dict,
          "models":       list,
          "signals":      list,
          "metadata":     dict,
          "processingMs": int,
          "source":       str,
        }
    """
    t0 = time.time()

    # ── Decode ────────────────────────────────────────────────────────────────
    try:
        image, raw_bytes = _decode_image(image_b64)
    except ValueError as exc:
        return {
            "trustScore": 50, "ai_percent": 50.0, "real_percent": 50.0,
            "confidence": 0.0, "verdict": _verdict(50),
            "models": [], "signals": [],
            "metadata": {"error": str(exc)},
            "processingMs": _ms(t0), "source": "error",
        }

    # ── EXIF (sync, fast) ────────────────────────────────────────────────────
    exif_result   = _exif_analysis(raw_bytes)

    # ── Pixel forensics (sync but CPU-bound → thread) ─────────────────────────
    pixel_result  = await asyncio.to_thread(_pixel_forensics, image)

    # ── CLIP inference ────────────────────────────────────────────────────────
    if _model is not None:
        try:
            clip_ai, clip_real, clip_conf = await asyncio.to_thread(_run_clip, image)
            source = "model"
        except Exception as exc:
            log.warning("CLIP inference error (%s) — using forensics only", exc)
            clip_ai, clip_real, clip_conf = await asyncio.to_thread(
                _heuristic_fallback, image_b64, raw_bytes
            )
            source = "heuristic-fallback"
    else:
        clip_ai, clip_real, clip_conf = await asyncio.to_thread(
            _heuristic_fallback, image_b64, raw_bytes
        )
        source = "heuristic"

    # ── Combine signals ───────────────────────────────────────────────────────
    # Weights: CLIP (50%), pixel forensics (30%), EXIF (20%)
    pixel_ai  = pixel_result["score"]          # 0–100, higher = more AI
    exif_ai   = exif_result["score"]           # 0–100, higher = more AI

    combined_ai = (
        clip_ai   * 0.50 +
        pixel_ai  * 0.30 +
        exif_ai   * 0.20
    )
    ai_pct    = round(min(98, max(2, combined_ai)), 2)
    real_pct  = round(100 - ai_pct, 2)

    # Confidence: average of CLIP confidence and pixel decisiveness
    pixel_conf   = round(abs(pixel_ai / 100 - 0.5) * 2, 4)
    confidence   = round((clip_conf * 0.6 + pixel_conf * 0.4), 4)
    trust_score  = round(real_pct)

    # ── Merge all signals ─────────────────────────────────────────────────────
    all_signals = (
        pixel_result.get("signals", []) +
        exif_result.get("signals",  [])
    )

    return {
        "trustScore":   trust_score,
        "ai_percent":   ai_pct,
        "real_percent": real_pct,
        "confidence":   confidence,
        "verdict":      _verdict(trust_score),
        "models": [
            {
                "modelId":    MODEL_ID,
                "modelName":  MODEL_NAME,
                "weight":     MODEL_WEIGHT,
                "ai_percent": clip_ai,
                "real_percent": clip_real,
                "score":      round(clip_real),
                "confidence": clip_conf,
                "source":     source,
            },
            {
                "modelId":    "pixel-forensics",
                "modelName":  "Pixel Forensics",
                "weight":     0.30,
                "ai_percent": pixel_ai,
                "real_percent": round(100 - pixel_ai, 2),
                "score":      round(100 - pixel_ai),
                "confidence": pixel_conf,
                "source":     "local",
            },
        ],
        "signals":      all_signals,
        "metadata":     exif_result.get("metadata", {}),
        "processingMs": _ms(t0),
        "source":       source,
    }


# ── Helpers ───────────────────────────────────────────────────────────────────

VERDICT_THRESHOLDS = [
    (85, "AUTHENTIC",    "#00ff9d"),
    (70, "LIKELY REAL",  "#7aff6e"),
    (50, "UNCERTAIN",    "#ffb300"),
    (30, "SUSPICIOUS",   "#ff7a00"),
    ( 0, "AI-GENERATED", "#ff3d5a"),
]


def _verdict(score: int) -> dict:
    for threshold, label, color in VERDICT_THRESHOLDS:
        if score >= threshold:
            return {"label": label, "color": color}
    return {"label": "UNKNOWN", "color": "#00e5ff"}


def _ms(t0: float) -> int:
    return round((time.time() - t0) * 1000)
# ══════════════════════════════════════════════════════════
#  FastAPI wrapper  —  image-service
#  Exposes:  GET /health   POST /detect
#  Body:     { "image": "<base64 or data-URI>" }
# ══════════════════════════════════════════════════════════

import os
from contextlib import asynccontextmanager
import uvicorn
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, field_validator


@asynccontextmanager
async def lifespan(app: FastAPI):
    log.info("image-service ready  model=%s  pipeline=%s",
             MODEL_ID, "loaded" if _model else "heuristic-only")
    yield


app = FastAPI(title="Image Detection Service", version="1.0.0", lifespan=lifespan)
app.add_middleware(CORSMiddleware,
    allow_origins=["*"], allow_credentials=True,
    allow_methods=["*"], allow_headers=["*"])


class ImageRequest(BaseModel):
    image: str

    @field_validator("image")
    @classmethod
    def _check(cls, v: str) -> str:
        if not v or len(v.strip()) < 20:
            raise ValueError("image must be a non-empty base64 string")
        return v.strip()


@app.get("/health")
async def health():
    return {
        "status":   "ok",
        "service":  "image-detection",
        "model":    MODEL_ID,
        "pipeline": _model is not None,
    }


@app.post("/detect")
async def detect(req: ImageRequest):
    result = await analyze_image(req.image)
    return result   # analyze_image already returns full structured response


if __name__ == "__main__":
    uvicorn.run("main:app",
                host="0.0.0.0",
                port=int(os.getenv("PORT", 8003)),
                reload=False)