"""
AI Image Detection Service
══════════════════════════════════════════════════════════════
Runtime       : ONNX Runtime thuần CPU  (KHÔNG có torch)
Primary model : openai/clip-vit-base-patch16  (ONNX export)
Forensics     : DCT, noise uniformity, colour channel correlation
EXIF          : software markers, missing GPS, no camera info

Thay đổi so với bản gốc
────────────────────────
- Bỏ hoàn toàn torch + transformers
- Dùng onnxruntime + tokenizers + Pillow để chạy CLIP
- RAM ~220–300MB thay vì ~600MB+
"""

from __future__ import annotations

import asyncio
import base64
import io
import json
import logging
import math
import time
from typing import Any

import numpy as np

log = logging.getLogger("aiproof.ai_image")

# ── Model config ──────────────────────────────────────────────────────────────

MODEL_ID     = "openai/clip-vit-base-patch16"
MODEL_NAME   = "CLIP ViT-B/16"
MODEL_WEIGHT = 0.40

# ── Zero-shot prompt groups ───────────────────────────────────────────────────

_REAL_PROMPTS = [
    "a real photograph taken by a camera",
    "a natural photo with realistic lighting and texture",
    "an authentic image captured by a human photographer",
]

_AI_PROMPTS = [
    "an AI-generated image created by a neural network",
    "a synthetic image generated by a diffusion model",
    "a computer-generated deepfake or GAN image",
]

_AI_SOFTWARE_MARKERS = [
    "stable diffusion", "midjourney", "dalle", "dall-e",
    "firefly", "gen-2", "runway", "comfy", "automatic1111",
    "novelai", "invoke", "dream", "artbreeder",
]

# ── ONNX session globals ──────────────────────────────────────────────────────

_VISUAL_SESSION   = None   # onnxruntime.InferenceSession  (visual encoder)
_TEXT_SESSION     = None   # onnxruntime.InferenceSession  (text encoder)
_TOKENIZER        = None   # tokenizers.Tokenizer
_load_error: str | None = None

# Hugging Face ONNX repo cho CLIP (đã có sẵn file .onnx)
_ONNX_MODEL_REPO  = "Xenova/clip-vit-base-patch16"


def _load_model() -> None:
    """
    Tải CLIP ONNX từ repo Xenova/clip-vit-base-patch16 trên HuggingFace.
    Repo này đã có sẵn file .onnx — không cần convert.
    Không import torch hay transformers.
    """
    global _VISUAL_SESSION, _TEXT_SESSION, _TOKENIZER, _load_error

    try:
        import onnxruntime as ort
        from tokenizers import Tokenizer
        from huggingface_hub import hf_hub_download

        log.info("Downloading CLIP ONNX from %s …", _ONNX_MODEL_REPO)
        t0 = time.time()

        # 1. Tokenizer
        tok_path   = hf_hub_download(_ONNX_MODEL_REPO, "tokenizer.json")
        _TOKENIZER = Tokenizer.from_file(tok_path)
        _TOKENIZER.enable_truncation(max_length=77)   # CLIP max text tokens
        _TOKENIZER.enable_padding(length=77)

        # 2. ONNX sessions
        opts = ort.SessionOptions()
        opts.intra_op_num_threads = 2

        visual_path = hf_hub_download(_ONNX_MODEL_REPO, "onnx/vision_model.onnx")
        text_path   = hf_hub_download(_ONNX_MODEL_REPO, "onnx/text_model.onnx")

        _VISUAL_SESSION = ort.InferenceSession(
            visual_path, sess_options=opts,
            providers=["CPUExecutionProvider"],
        )
        _TEXT_SESSION = ort.InferenceSession(
            text_path, sess_options=opts,
            providers=["CPUExecutionProvider"],
        )

        log.info("CLIP ONNX loaded in %.1fs", time.time() - t0)

    except Exception as exc:
        _load_error = str(exc)
        log.warning("Could not load CLIP (%s) — pixel-forensics only", exc)


_load_model()


# ── Image decoding ────────────────────────────────────────────────────────────

def _decode_image(image_b64: str):
    from PIL import Image
    if "," in image_b64:
        image_b64 = image_b64.split(",", 1)[1]
    try:
        raw   = base64.b64decode(image_b64)
        image = Image.open(io.BytesIO(raw)).convert("RGB")
        return image, raw
    except Exception as exc:
        raise ValueError(f"Cannot decode image: {exc}") from exc


# ── Image preprocessing (thay CLIPProcessor) ─────────────────────────────────

def _preprocess_image(image) -> np.ndarray:
    """
    Resize → center crop → normalize theo CLIP convention.
    Trả về array shape (1, 3, 224, 224) float32.
    """
    from PIL import Image

    # Resize ngắn nhất = 224
    w, h = image.size
    scale = 224 / min(w, h)
    new_w, new_h = int(w * scale), int(h * scale)
    image = image.resize((new_w, new_h), Image.BICUBIC)

    # Center crop 224x224
    left = (new_w - 224) // 2
    top  = (new_h - 224) // 2
    image = image.crop((left, top, left + 224, top + 224))

    arr = np.array(image, dtype=np.float32) / 255.0

    # CLIP normalization
    mean = np.array([0.48145466, 0.4578275,  0.40821073], dtype=np.float32)
    std  = np.array([0.26862954, 0.26130258, 0.27577711], dtype=np.float32)
    arr  = (arr - mean) / std

    # HWC → CHW → NCHW
    arr = arr.transpose(2, 0, 1)[np.newaxis, :]
    return arr


# ── CLIP ONNX inference ───────────────────────────────────────────────────────

def _softmax(x: np.ndarray) -> np.ndarray:
    e = np.exp(x - x.max())
    return e / e.sum()


def _run_clip(image) -> tuple[float, float, float]:
    """
    Blocking CLIP inference qua ONNX Runtime.
    Trả về (ai_pct, real_pct, confidence).
    """
    all_prompts = _REAL_PROMPTS + _AI_PROMPTS
    n_real      = len(_REAL_PROMPTS)

    # ── Text encoding ──────────────────────────────────────────────────
    enc          = _TOKENIZER.encode_batch(all_prompts)
    input_ids    = np.array([e.ids            for e in enc], dtype=np.int64)
    attn_mask    = np.array([e.attention_mask for e in enc], dtype=np.int64)

    text_feeds = {"input_ids": input_ids, "attention_mask": attn_mask}
    text_input_names = [i.name for i in _TEXT_SESSION.get_inputs()]
    if "token_type_ids" in text_input_names:
        text_feeds["token_type_ids"] = np.zeros_like(input_ids)

    text_embeds = _TEXT_SESSION.run(None, text_feeds)[0]  # (n_prompts, dim)

    # ── Visual encoding ────────────────────────────────────────────────
    pixel_values  = _preprocess_image(image)
    visual_embeds = _VISUAL_SESSION.run(None, {"pixel_values": pixel_values})[0]  # (1, dim)

    # ── Cosine similarity → softmax → probabilities ────────────────────
    # Normalize
    text_norm   = text_embeds  / (np.linalg.norm(text_embeds,  axis=1, keepdims=True) + 1e-8)
    visual_norm = visual_embeds / (np.linalg.norm(visual_embeds, axis=1, keepdims=True) + 1e-8)

    logits = (visual_norm @ text_norm.T)[0] * 100.0   # scale như CLIP gốc
    probs  = _softmax(logits)

    real_prob = float(probs[:n_real].mean())
    ai_prob   = float(probs[n_real:].mean())

    total    = real_prob + ai_prob
    ai_pct   = round((ai_prob  / total) * 100, 2) if total else 50.0
    real_pct = round((real_prob / total) * 100, 2) if total else 50.0
    confidence = round(abs(ai_pct / 100 - 0.5) * 2, 4)

    return ai_pct, real_pct, confidence


# ── Pixel forensics ───────────────────────────────────────────────────────────

def _dct1d(x: np.ndarray) -> np.ndarray:
    n      = len(x)
    result = np.zeros(n)
    for k in range(n):
        result[k] = sum(
            x[i] * math.cos(math.pi * k * (2 * i + 1) / (2 * n))
            for i in range(n)
        )
    return result


def _dct2(block: np.ndarray) -> np.ndarray:
    n      = block.shape[0]
    result = np.zeros_like(block)
    for i in range(n):
        result[i] = _dct1d(block[i])
    for j in range(n):
        result[:, j] = _dct1d(result[:, j])
    return result


def _pixel_forensics(image) -> dict[str, Any]:
    img_arr = np.array(image, dtype=np.float32)
    h, w, _ = img_arr.shape
    grey     = img_arr.mean(axis=2)
    signals  = []
    scores   = []

    # 1. DCT high-frequency energy
    try:
        hf_ratios = []
        for _ in range(16):
            ry = max(0, min(h - 8, int(np.random.rand() * (h - 8))))
            rx = max(0, min(w - 8, int(np.random.rand() * (w - 8))))
            block = grey[ry:ry+8, rx:rx+8]
            dct   = _dct2(block)
            dc    = float(dct[0, 0] ** 2)
            ac    = float((dct ** 2).sum() - dc)
            hf_ratios.append(ac / (dc + 1e-6))
        avg_hf = float(np.mean(hf_ratios))
        if avg_hf < 0.12:
            scores.append(80.0)
            signals.append({"type": "dct-frequency", "label": "Unnaturally smooth frequency spectrum", "strength": 0.85})
        elif avg_hf < 0.22:
            scores.append(55.0)
            signals.append({"type": "dct-frequency", "label": "Low high-frequency energy", "strength": 0.55})
        else:
            scores.append(25.0)
            signals.append({"type": "dct-frequency", "label": "Natural camera noise pattern", "strength": 0.20})
    except Exception as e:
        log.debug("DCT failed: %s", e)

    # 2. Noise uniformity
    try:
        ch, cw = h // 4, w // 4
        local_stds = [
            float(np.std(grey[i*ch:(i+1)*ch, j*cw:(j+1)*cw]))
            for i in range(4) for j in range(4)
        ]
        sof_stds = float(np.std(local_stds))
        if sof_stds < 3.0:
            scores.append(75.0)
            signals.append({"type": "noise-uniformity", "label": "Suspiciously uniform noise across regions", "strength": 0.80})
        elif sof_stds < 8.0:
            scores.append(45.0)
            signals.append({"type": "noise-uniformity", "label": "Slightly uniform noise distribution", "strength": 0.45})
        else:
            scores.append(20.0)
            signals.append({"type": "noise-uniformity", "label": "Natural regional noise variation", "strength": 0.15})
    except Exception as e:
        log.debug("Noise failed: %s", e)

    # 3. Colour channel correlation
    try:
        r = img_arr[:, :, 0].flatten()
        g = img_arr[:, :, 1].flatten()
        b = img_arr[:, :, 2].flatten()
        avg_corr = (abs(float(np.corrcoef(r, g)[0, 1])) + abs(float(np.corrcoef(r, b)[0, 1]))) / 2
        if avg_corr > 0.97:
            scores.append(70.0)
            signals.append({"type": "colour-correlation", "label": "Unnaturally high channel correlation", "strength": 0.75})
        elif avg_corr > 0.90:
            scores.append(40.0)
            signals.append({"type": "colour-correlation", "label": "Elevated colour channel correlation", "strength": 0.40})
        else:
            scores.append(15.0)
    except Exception as e:
        log.debug("Colour failed: %s", e)

    composite = round(sum(scores) / len(scores), 2) if scores else 50.0
    return {"score": composite, "signals": signals}


# ── EXIF analysis ─────────────────────────────────────────────────────────────

def _exif_analysis(raw_bytes: bytes) -> dict[str, Any]:
    signals  = []
    metadata = {}
    score    = 0.0

    try:
        from PIL import Image, ExifTags
        img      = Image.open(io.BytesIO(raw_bytes))
        exif_raw = img._getexif() if hasattr(img, "_getexif") else None
        exif     = {}
        if exif_raw:
            exif = {ExifTags.TAGS.get(k, k): v for k, v in exif_raw.items()}

        if not exif:
            score += 25
            signals.append({"type": "exif-absent", "label": "No EXIF metadata (common in AI images)", "strength": 0.60})
            metadata["hasExif"] = False
        else:
            metadata["hasExif"] = True
            software = str(exif.get("Software", "")).lower()
            metadata["software"] = exif.get("Software")
            for marker in _AI_SOFTWARE_MARKERS:
                if marker in software:
                    score += 60
                    signals.append({"type": "exif-software", "label": f"AI software detected: {exif.get('Software')}", "strength": 0.95})
                    break
            if not exif.get("Make") and not exif.get("Model"):
                score += 20
                signals.append({"type": "exif-no-camera", "label": "No camera make/model in metadata", "strength": 0.50})
            if "GPSInfo" not in exif:
                score += 10
                signals.append({"type": "exif-no-gps", "label": "No GPS data (expected in phone photos)", "strength": 0.30})
            metadata["cameraMake"]  = exif.get("Make")
            metadata["cameraModel"] = exif.get("Model")
            metadata["hasGPS"]      = "GPSInfo" in exif

        metadata.update({"width": img.width, "height": img.height, "format": img.format})

    except Exception as exc:
        log.debug("EXIF error: %s", exc)

    return {"score": round(min(100, score), 2), "signals": signals, "metadata": metadata}


# ── Heuristic fallback ────────────────────────────────────────────────────────

def _heuristic_fallback(image_b64: str, raw_bytes: bytes) -> tuple[float, float, float]:
    sample = raw_bytes[:65536]
    if not sample:
        return 50.0, 50.0, 0.3
    counts  = [0] * 256
    for b in sample:
        counts[b] += 1
    n       = len(sample)
    entropy = -sum((c / n) * math.log2(c / n) for c in counts if c > 0)
    ai_pct  = 25.0 if entropy > 7.6 else (45.0 if entropy > 7.0 else 65.0)
    return round(ai_pct, 2), round(100 - ai_pct, 2), 0.35


# ── Verdict helpers ───────────────────────────────────────────────────────────

VERDICT_THRESHOLDS = [
    (85, "AUTHENTIC",    "#00ff9d"),
    (70, "LIKELY REAL",  "#7aff6e"),
    (50, "UNCERTAIN",    "#ffb300"),
    (30, "SUSPICIOUS",   "#ff7a00"),
    ( 0, "AI-GENERATED", "#ff3d5a"),
]


def _verdict(score: int) -> dict:
    for threshold, label, color in VERDICT_THRESHOLDS:
        if score >= threshold:
            return {"label": label, "color": color}
    return {"label": "UNKNOWN", "color": "#00e5ff"}


def _ms(t0: float) -> int:
    return round((time.time() - t0) * 1000)


# ── Public entry point ────────────────────────────────────────────────────────

async def analyze_image(image_b64: str) -> dict[str, Any]:
    t0 = time.time()

    try:
        image, raw_bytes = _decode_image(image_b64)
    except ValueError as exc:
        return {
            "trustScore": 50, "ai_percent": 50.0, "real_percent": 50.0,
            "confidence": 0.0, "verdict": _verdict(50),
            "models": [], "signals": [],
            "metadata": {"error": str(exc)},
            "processingMs": _ms(t0), "source": "error",
        }

    exif_result  = _exif_analysis(raw_bytes)
    pixel_result = await asyncio.to_thread(_pixel_forensics, image)

    if _VISUAL_SESSION is not None and _TEXT_SESSION is not None:
        try:
            clip_ai, clip_real, clip_conf = await asyncio.to_thread(_run_clip, image)
            source = "onnx-model"
        except Exception as exc:
            log.warning("CLIP ONNX error (%s) — heuristic fallback", exc)
            clip_ai, clip_real, clip_conf = _heuristic_fallback(image_b64, raw_bytes)
            source = "heuristic-fallback"
    else:
        clip_ai, clip_real, clip_conf = _heuristic_fallback(image_b64, raw_bytes)
        source = "heuristic"

    pixel_ai     = pixel_result["score"]
    exif_ai      = exif_result["score"]
    combined_ai  = clip_ai * 0.50 + pixel_ai * 0.30 + exif_ai * 0.20
    ai_pct       = round(min(98, max(2, combined_ai)), 2)
    real_pct     = round(100 - ai_pct, 2)
    pixel_conf   = round(abs(pixel_ai / 100 - 0.5) * 2, 4)
    confidence   = round(clip_conf * 0.6 + pixel_conf * 0.4, 4)
    trust_score  = round(real_pct)

    return {
        "trustScore":   trust_score,
        "ai_percent":   ai_pct,
        "real_percent": real_pct,
        "confidence":   confidence,
        "verdict":      _verdict(trust_score),
        "models": [
            {
                "modelId":     MODEL_ID,
                "modelName":   MODEL_NAME,
                "weight":      MODEL_WEIGHT,
                "ai_percent":  clip_ai,
                "real_percent": clip_real,
                "score":       round(clip_real),
                "confidence":  clip_conf,
                "source":      source,
            },
            {
                "modelId":     "pixel-forensics",
                "modelName":   "Pixel Forensics",
                "weight":      0.30,
                "ai_percent":  pixel_ai,
                "real_percent": round(100 - pixel_ai, 2),
                "score":       round(100 - pixel_ai),
                "confidence":  pixel_conf,
                "source":      "local",
            },
        ],
        "signals":      pixel_result.get("signals", []) + exif_result.get("signals", []),
        "metadata":     exif_result.get("metadata", {}),
        "processingMs": _ms(t0),
        "source":       source,
    }


# ══════════════════════════════════════════════════════════
#  FastAPI  —  GET /health   POST /detect
# ══════════════════════════════════════════════════════════

import os
from contextlib import asynccontextmanager
import uvicorn
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, field_validator


@asynccontextmanager
async def lifespan(app: FastAPI):
    log.info("image-service ready  model=%s  runtime=%s",
             MODEL_ID, "onnx" if _VISUAL_SESSION else "heuristic-only")
    yield


app = FastAPI(title="Image Detection Service", version="1.0.0", lifespan=lifespan)
app.add_middleware(CORSMiddleware,
    allow_origins=["*"], allow_credentials=True,
    allow_methods=["*"], allow_headers=["*"])


class ImageRequest(BaseModel):
    image: str

    @field_validator("image")
    @classmethod
    def _check(cls, v: str) -> str:
        if not v or len(v.strip()) < 20:
            raise ValueError("image must be a non-empty base64 string")
        return v.strip()


@app.get("/health")
async def health():
    return {
        "status":   "ok",
        "service":  "image-detection",
        "model":    MODEL_ID,
        "runtime":  "onnx" if _VISUAL_SESSION else "heuristic",
        "pipeline": _VISUAL_SESSION is not None,
    }


@app.post("/detect")
async def detect(req: ImageRequest):
    return await analyze_image(req.image)


if __name__ == "__main__":
    uvicorn.run("main:app",
                host="0.0.0.0",
                port=int(os.getenv("PORT", 8003)),
                reload=False)
